AWSTemplateFormatVersion: '2010-09-09'
Description: 'options v2 app

  '
Globals:
  Function:
    Timeout: 3
Outputs:
  DeleteOptionsAPI:
    Description: API Gateway endpoint URL for Prod stage for Expired Options function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/optionsDelete/{optionsKey}
  DeleteOptionsFunction:
    Description: Delete Options
    Value:
      Fn::GetAtt:
      - DeleteOptionsFunction
      - Arn
  DeleteOptionsFunctionIamRole:
    Description: Implicit IAM Role created for expired options function
    Value:
      Fn::GetAtt:
      - DeleteOptionsFunctionRole
      - Arn
  ExpiredOptionsAPI:
    Description: API Gateway endpoint URL for Prod stage for Expired Options function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/optionsExpired/
  ExpiredOptionsFunction:
    Description: Expired Options
    Value:
      Fn::GetAtt:
      - ExpiredOptionsFunction
      - Arn
  ExpiredOptionsFunctionIamRole:
    Description: Implicit IAM Role created for expired options function
    Value:
      Fn::GetAtt:
      - ExpiredOptionsFunctionRole
      - Arn
  OptionsAPI:
    Description: API Gateway endpoint URL for Prod stage for Options function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/options/
  OptionsFunction:
    Description: options v2 Lambda Function ARN
    Value:
      Fn::GetAtt:
      - OptionsFunction
      - Arn
  OptionsFunctionIamRole:
    Description: Implicit IAM Role created for options v2 function
    Value:
      Fn::GetAtt:
      - OptionsFunctionRole
      - Arn
Resources:
  DeleteOptionsFunction:
    Properties:
      CodeUri: s3://larsbucket1/279a96ae652b33c27d438655b7f219ac
      Events:
        Options:
          Properties:
            Method: delete
            Path: /optionsDelete/{optionsKey}
          Type: Api
      Handler: handler.deleteOptions_handler
      Runtime: python3.7
    Type: AWS::Serverless::Function
  ExpiredOptionsFunction:
    Properties:
      CodeUri: s3://larsbucket1/9f36189b31267c0819953ad49920a243
      Events:
        Options:
          Properties:
            Method: get
            Path: /optionsExpired
          Type: Api
      Handler: handler.expiredOptions_handler
      Runtime: python3.7
    Type: AWS::Serverless::Function
  OptionsFunction:
    Properties:
      CodeUri: s3://larsbucket1/71aa8b60fa93e0adbffd8ad9745100cb
      Events:
        Options:
          Properties:
            Method: get
            Path: /options
          Type: Api
      Handler: handler.lambda_handler
      Runtime: python3.7
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
