AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  options v2 app

Globals:
  Function:
    Timeout: 3

Resources:
  OptionsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: handler.lambda_handler
      Runtime: python3.7
      Events:
        Options:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /options
            Method: get
  ExpiredOptionsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: handler.expiredOptions_handler
      Runtime: python3.7
      Events:
        Options:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /optionsExpired
            Method: get

Outputs:
  OptionsAPI:
    Description: "API Gateway endpoint URL for Prod stage for Options function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/options/"
  OptionsFunction:
    Description: "options v2 Lambda Function ARN"
    Value: !GetAtt OptionsFunction.Arn
  OptionsFunctionIamRole:
    Description: "Implicit IAM Role created for options v2 function"
    Value: !GetAtt OptionsFunctionRole.Arn

  ExpiredOptionsAPI:
    Description: "API Gateway endpoint URL for Prod stage for Expired Options function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/optionsExpired/"
  ExpiredOptionsFunction:
    Description: "Expired Options"
    Value: !GetAtt ExpiredOptionsFunction.Arn
  ExpiredOptionsFunctionIamRole:
    Description: "Implicit IAM Role created for expired options function"
    Value: !GetAtt ExpiredOptionsFunctionRole.Arn
